### ISSUE TITLE
Small bugs in the code

### ISSUE THREAD

**Issue by byby221b** [cimeister/pu-learning#1]
Hi~ 
Thank you for your implementation. But I think that there might be a small bug in the code.
The problem appears on lines 30 to 32 of loss.py. Sigmoid(0)=0.5 rather than 0. Therefore , when unlabeled[i]==0, which means sample i is a positive sample, self.loss_func(-unlabeled*inp)[i] will be 0.5 rather than 0. It may be unreasonable since we should compute y_unlabeled with only unlabeled data. 
I suggest that the code should be changed into:
`y_positive = self.loss_func(positive * inp) * positive`
`y_positive_inv = self.loss_func(-positive * inp) * positive`
`y_unlabeled = self.loss_func(-unlabeled * inp) * unlabeled`

Best wishes!

**Comment by cimeister** [comment]
Hello, thank you for the insight! I believe you are right; it has now been changed. 
4e99cdd8097a3a3894a40e1e9eb5e08569ec2854
